version: '3.3'

services:
  avtosale-next:
    container_name: avto-baraka-next
    restart: always
    image: node:20.10.0
    ports:
      - 4000:3000
    environment:
      - PORT=3000
    volumes:
      - ./:/usr/src/avtobaraka-next
    working_dir: /usr/src/avtobaraka-next
    networks:
      - client-network
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge
# avtobaraka-api: localhost:4000 <=> 3000
# avtobaraka-api: localhost:4004 <=> 3004
# avtobaraka-batch: localhost:4005 <=> 3005
